[build]
  command = "cd site && yarn build"
  publish = "./site/public"

[build.environment]
  NETLIFY_USE_YARN = "true"

[context.production]
  [context.production.environment]
    CONTENTFUL_SPACE_ID="h0va7bmfxi3c"
    CONTENTFUL_ACCESS_TOKEN="zaWPmkMgHj8hbb1N0m_fnYOFRowxWyavzSpHLd_7kU8"
    GATSBY_ALGOLIA_APP_ID="8HXM9UOFDB"
    GATSBY_ALGOLIA_SEARCH_KEY="c42bdcaddd73f85f03a36f8920cc25e6"
    ALGOLIA_ADMIN_KEY="6b9524f4e03ec12e0a1eeb7f55e70147"
    GATSBY_ALGOLIA_INDEX_NAME="Posts"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

  [[redirects]]
  from = "/authors"
  to = "/404"
  status = 301
  force = true